### ISSUE TITLE
Use thirdparty when ASIO/TinyXML2 is not found

### ISSUE THREAD

**Issue by Karsten1987** [ros2/Fast-RTPS#1]
Title should be self-explanatory.
I don't have the two deps installed in my machine, but expected Fast-RTPS to compile with the thirdparty provided libs.

**Comment by mikaelarguedas** [comment]
Do you have anything in your Fast-RTPS/thirdparty/asio folder ? You need to clone the Fast-RTPS repository recursively for those to be cloned

**Comment by Karsten1987** [comment]
i would have expect to set the `THIRDPARTY` flag if not found on PATH, and fast-rtps cmake modules do pull the deps in.

https://github.com/ros2/Fast-RTPS/blob/ros2/cmake/dev/eprosima_libraries.cmake#L156-L160

**Comment by mikaelarguedas** [comment]
I see your point. Not sure how we want to proceed here, this fork is mostly to test the cmake logic to make sure we can find our chocolatey packages, I don't think that we should modify the rest of the CMake logic here and diverge more from master.

Especially the git submodule logic you pointed out explicitly ignores Windows so we would need to change that as well if we want to have the behavior you expect on all our supported platforms. This ticket could be opened upstream to see if eProsima agrees to clone repositories in the build process even when user didn't explicitly asked to (which I don't think is good practice in general as @tfoote pointed out in https://github.com/ros/rosdistro/pull/14398#issuecomment-291604643).

**Comment by Karsten1987** [comment]
I admit I didn't follow the complete process about the latest changes of fast-rtps. I know the initial conflict was clearly vcs not pulling in submodules, but also with the idea in mind of not compiling Tinyxml and ASIO from source if these libs are already installed. With that being said, the inverse should still hold, that is, if these libs are not available, the package compiles the submodules. 

But @mikaelarguedas, I agree with you that this ticket has its right place upstream. Just wanted to mention it here.

**Comment by mikaelarguedas** [comment]
> With that being said, the inverse should still hold, that is, if these libs are not available, the package compiles the submodules

agreed. And that's what Fast-RTPS does. If the code is in your CMake project it will compile them.
But that doesn't imply that CMake should be pulling thirdparty libraries during the build process without you explicitly asking for it. So I think that Fast-RTPS is doing the right thing here.

We can definitely continue the discussion upstream if anybody else think that the current behavior should be changed.

**Comment by nuclearsandwich** [comment]
> With that being said, the inverse should still hold, that is, if these libs are not available, the package compiles the submodules.

If this is what the Fast-RTPS maintainers want, we should make sure nothing we contribute negatively affects that, but I'm really inclined to only test, recommend, and officially support one path for ROS 2 users (at least on Windows, I have less of a stake in the MacOS and LInux side) through Beta 2.

Short of uninstalling and reinstalling the chocolatey packages during different builds (which would require Windows admin escalation) there is no way to vary their availability except to pick a Windows machine to permanently uninstall them and have it be the test of the built in submodule use. But because Jenkins uses the first available node rather than round-robining them, builds will skew heavily toward one case or the other rather than split at a desired ratio.

**Comment by Karsten1987** [comment]
There is no direct action required here on that point, I just wanted to
mention it and see if this was intended or not.
We can close this issues as well.

**Comment by Karsten1987** [comment]
i am closing this given that the current behavior is expected.
